# try finally
# 由于没有except去捕获，则会抛出KeyboardInterrupt
# 注意，是finally的代码先执行，再抛except
>>> try:
...     raise KeyboardInterrupt
... finally:
...     print 'Goodbye, world!'
...
Goodbye, world!
KeyboardInterrupt
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>

# try except else finally
# 注意，是finally的代码先执行，再抛except
>>> def divide(x, y):
...     try:
...         result = x / y
...     except ZeroDivisionError:
...         print "division by zero!"
...     else:
...         print "result is", result
...     finally:
...         print "executing finally clause"
...
>>> divide(2, 1)
result is 2
executing finally clause
>>> divide(2, 0)            # 捕获ZeroDivisionError异常
division by zero!
executing finally clause
>>> divide("2", "1")        # 会抛出TypeError的异常
executing finally clause
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in divide
TypeError: unsupported operand type(s) for /: 'str' and 'str'